### ISSUE TITLE
✨ [ENHANCEMENT] - Improve the UI of the Contributors page

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#1]
**Description:**

Improve the UI of the contributors' page.

**Tasks:**

- [ ] Add a title to the page.
- [ ] Add a border for every contributor.
- [ ] Add extra information, such as their commits to the project and their role (admin or contributor).

It should look like this 
![image](https://github.com/Pinaka-Pani-18/Public-Codebases/assets/102857774/6c4ba8ee-2db2-48f2-afea-ee2888e08bc6)

**Comment by Sh4dab** [comment]
Assign this to me

**Comment by Pinaka-Pani-18** [comment]
> Assign this to me

Assigned to you @Sh4dab, start working on it.
