### ISSUE TITLE
✨ [ENHANCEMENT] - Improve the Navbar 

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#15]
**Description:**
The current navbar is functional, but when it's active on any page, the active page in the navbar should have a different color. Additionally, add some creative hover effects to the links and include a relevant icon in the place of logo and kept the name unchanged.

**Tasks:**
- [ ] Enhance the active page styling in the navbar.
- [ ] Implement creative hover effects for links.
- [ ] Add a relevant icon in the place of logo.

**Comment by awsmdeep** [comment]
hey @Pinaka-Pani-18  i hope you are doing well, can you please assign me to this work

**Comment by Ferdinand-Ogama** [comment]
Hello, kindly assign me this issue.

**Comment by Pinaka-Pani-18** [comment]
> hey @Pinaka-Pani-18 i hope you are doing well, can you please assign me to this work

Assigned to you @awsmdeep , you can start working on it.

**Comment by Pinaka-Pani-18** [comment]
> Hello, kindly assign me this issue.

Hi @Ferdinand-Ogama as we are assigning issues on a first-come, first-served basis, please check other issues and leave a comment there. I will then assign you, or you can identify any issue and create one.

**Comment by Pinaka-Pani-18** [comment]
> hey @Pinaka-Pani-18 i hope you are doing well, can you please assign me to this work

any updates @awsmdeep ?

**Comment by Pree46** [comment]
Hey can you assign this task to me. If no one else is assigned at the moment.

**Comment by Pree46** [comment]
I have improved the navbar and designed a logo and added the same to the header and the footer
Kindly go through it and let me know if i need to change anything, thank you for letting me work on this issue.
