### ISSUE TITLE
💡 [FEATURE] - Create a Logo

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#2]
**Description:** 
Design a creative logo that aligns with our project's theme. Use Figma or related tools to create an effective logo.

**Tasks:**

- [ ]  Create a creative logo that aligns with our project's theme.
- [ ] After creating the logo, add it to the `readme.md` file, `header.jsx` file, `footer.jsx`, and use it as the favicon.
- [ ] The logo should be created as .png format

**Comment by aryankshl** [comment]
hey @Pinaka-Pani-18 can you assign this to me?

**Comment by Pinaka-Pani-18** [comment]
> hey @Pinaka-Pani-18 can you assign this to me?

Assigned to you @aryankshl, please make sure you complete all the 3 tasks listed in this issue and make a PR after completing this issue.

**Comment by aryankshl** [comment]
hey @Pinaka-Pani-18 I am working on it. It will be done very soon

**Comment by aryankshl** [comment]
hey @Pinaka-Pani-18 its done. You can check and merge it now.

**Comment by Goldphic** [comment]
I'll like to contribute@Pinaka-Pani-18
